name: Azure Container Build and Push Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: unfignitech.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t unfignitech.azurecr.io/k9ocrs:${{ github.sha }} .
        docker push unfignitech.azurecr.io/k9ocrs:${{ github.sha }}